import type { CarDefinition } from "../models.js";

/**
 * Evo2 5600kv — 1:28-scale RWD mini chassis (5600 kV motor class).
 *
 * A popular competitive class in micro RC racing, typically running
 * 5600 kV brushless motors on RCP tile tracks. The car features a
 * standard t-plate front suspension, rear pod design, and is tuned
 * for high-grip short tracks.
 */
export const evo2_5600kv: CarDefinition = {
  id: "car-evo2-5600kv",
  slug: "evo2-5600kv",
  name: "Evo2 5600kv",
  manufacturer: "GL Racing",
  scale: "1:28",
  driveType: "RWD",

  capabilities: [
    // ── Chassis ───────────────────────────────────────────────
    {
      id: "chassis-plate",
      name: "Chassis Plate",
      category: "Chassis",
      valueType: "pick",
      options: [
        { label: "Standard FRP", value: "frp" },
        { label: "Carbon Fiber", value: "carbon" },
      ],
      defaultValue: "carbon",
    },
    {
      id: "motor-pod",
      name: "Motor Pod",
      category: "Chassis",
      valueType: "pick",
      options: [
        { label: "Standard", value: "standard" },
        { label: "Lightweight", value: "lightweight" },
      ],
      defaultValue: "standard",
    },

    // ── Front Suspension ──────────────────────────────────────
    {
      id: "front-spring",
      name: "Front Spring",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "Super Soft", value: "super-soft" },
        { label: "Soft", value: "soft" },
        { label: "Medium", value: "medium" },
        { label: "Hard", value: "hard" },
        { label: "Extra Hard", value: "x-hard" },
      ],
      defaultValue: "medium",
    },
    {
      id: "front-ride-height",
      name: "Front Ride Height",
      category: "Front Suspension",
      valueType: "numeric",
      min: 0,
      max: 6,
      step: 0.5,
      unit: "mm",
      defaultValue: 2.5,
    },
    {
      id: "front-camber",
      name: "Front Camber",
      category: "Front Suspension",
      valueType: "numeric",
      min: -3,
      max: 0,
      step: 0.5,
      unit: "°",
      defaultValue: -1,
      description: "Negative = top of tire leaning in",
    },
    {
      id: "front-toe",
      name: "Front Toe",
      category: "Front Suspension",
      valueType: "numeric",
      min: -2,
      max: 4,
      step: 0.5,
      unit: "°",
      defaultValue: 1,
      description: "Positive = toe-out",
    },
    {
      id: "front-caster",
      name: "Front Caster",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "0°", value: "0" },
        { label: "2°", value: "2" },
        { label: "4°", value: "4" },
        { label: "6°", value: "6" },
        { label: "8°", value: "8" },
      ],
      defaultValue: "4",
    },
    {
      id: "front-kingpin-angle",
      name: "Kingpin Angle",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "0°", value: "0" },
        { label: "3°", value: "3" },
        { label: "6°", value: "6" },
        { label: "8°", value: "8" },
      ],
      defaultValue: "6",
    },
    {
      id: "t-plate",
      name: "T-Plate",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "Soft (Thin)", value: "soft" },
        { label: "Medium (Standard)", value: "medium" },
        { label: "Hard (Thick)", value: "hard" },
      ],
      defaultValue: "medium",
      description: "T-plate stiffness controls front roll resistance",
    },
    {
      id: "front-knuckle",
      name: "Front Knuckle",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "Stock Plastic", value: "stock" },
        { label: "Aluminum", value: "aluminum" },
      ],
      defaultValue: "stock",
    },
    {
      id: "front-damper",
      name: "Front Damper",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "Friction Plate", value: "friction" },
        { label: "Oil Damper", value: "oil" },
      ],
      defaultValue: "friction",
    },

    // ── Rear Suspension ───────────────────────────────────────
    {
      id: "rear-spring",
      name: "Rear Spring",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "Super Soft", value: "super-soft" },
        { label: "Soft", value: "soft" },
        { label: "Medium", value: "medium" },
        { label: "Hard", value: "hard" },
        { label: "Extra Hard", value: "x-hard" },
      ],
      defaultValue: "medium",
    },
    {
      id: "rear-ride-height",
      name: "Rear Ride Height",
      category: "Rear Suspension",
      valueType: "numeric",
      min: 0,
      max: 6,
      step: 0.5,
      unit: "mm",
      defaultValue: 2.5,
    },
    {
      id: "rear-camber",
      name: "Rear Camber",
      category: "Rear Suspension",
      valueType: "numeric",
      min: -3,
      max: 0,
      step: 0.5,
      unit: "°",
      defaultValue: -1.5,
    },
    {
      id: "rear-damper",
      name: "Rear Damper",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "Friction", value: "friction" },
        { label: "Grease Damper", value: "grease" },
        { label: "Oil Damper", value: "oil" },
      ],
      defaultValue: "friction",
    },

    // ── Drivetrain ────────────────────────────────────────────
    {
      id: "pinion-gear",
      name: "Pinion Gear",
      category: "Drivetrain",
      valueType: "numeric",
      min: 6,
      max: 14,
      step: 1,
      unit: "T",
      defaultValue: 11,
    },
    {
      id: "spur-gear",
      name: "Spur Gear",
      category: "Drivetrain",
      valueType: "numeric",
      min: 38,
      max: 55,
      step: 1,
      unit: "T",
      defaultValue: 48,
    },
    {
      id: "diff-type",
      name: "Diff Type",
      category: "Drivetrain",
      valueType: "pick",
      options: [
        { label: "Spool (Locked)", value: "spool" },
        { label: "Ball Diff", value: "ball" },
        { label: "Gear Diff", value: "gear" },
      ],
      defaultValue: "ball",
    },
    {
      id: "diff-tension",
      name: "Diff Tension",
      category: "Drivetrain",
      valueType: "text",
      defaultValue: "medium",
      description: "Ball diff tightness — adjust until diff slips under hard throttle only",
    },

    // ── Tires & Wheels ────────────────────────────────────────
    {
      id: "front-tire",
      name: "Front Tire",
      category: "Tires & Wheels",
      valueType: "pick",
      options: [
        { label: "Marka V1 20 (Firm)", value: "marka-v1-20" },
        { label: "Marka V1 25 (Medium)", value: "marka-v1-25" },
        { label: "Marka V1 30 (Soft)", value: "marka-v1-30" },
        { label: "Kyosho Front (Stock)", value: "kyosho-front" },
      ],
      defaultValue: "marka-v1-25",
    },
    {
      id: "rear-tire",
      name: "Rear Tire",
      category: "Tires & Wheels",
      valueType: "pick",
      options: [
        { label: "Marka V1 20 (Firm)", value: "marka-v1-20" },
        { label: "Marka V1 25 (Medium)", value: "marka-v1-25" },
        { label: "Marka V1 30 (Soft)", value: "marka-v1-30" },
        { label: "Kyosho Rear (Stock)", value: "kyosho-rear" },
      ],
      defaultValue: "marka-v1-25",
    },
    {
      id: "front-wheel",
      name: "Front Wheel",
      category: "Tires & Wheels",
      valueType: "pick",
      options: [
        { label: "Standard Offset 0", value: "offset-0" },
        { label: "Narrow Offset +1", value: "offset-1" },
        { label: "Wide Offset -1", value: "offset-neg1" },
      ],
      defaultValue: "offset-0",
    },
    {
      id: "rear-wheel",
      name: "Rear Wheel",
      category: "Tires & Wheels",
      valueType: "pick",
      options: [
        { label: "Standard Offset 0", value: "offset-0" },
        { label: "Narrow Offset +1", value: "offset-1" },
        { label: "Wide Offset -1", value: "offset-neg1" },
      ],
      defaultValue: "offset-0",
    },

    // ── Electronics ───────────────────────────────────────────
    {
      id: "motor",
      name: "Motor",
      category: "Electronics",
      valueType: "text",
      defaultValue: "5600kv Brushless",
      description: "5600 kV class motor",
    },
    {
      id: "esc",
      name: "ESC",
      category: "Electronics",
      valueType: "text",
      defaultValue: "",
    },
    {
      id: "servo",
      name: "Servo",
      category: "Electronics",
      valueType: "text",
      defaultValue: "",
    },
    {
      id: "battery",
      name: "Battery",
      category: "Electronics",
      valueType: "text",
      defaultValue: "",
    },
    {
      id: "radio",
      name: "Radio System",
      category: "Electronics",
      valueType: "text",
      defaultValue: "",
    },
    {
      id: "receiver",
      name: "Receiver",
      category: "Electronics",
      valueType: "text",
      defaultValue: "",
    },
    {
      id: "transponder",
      name: "Transponder",
      category: "Electronics",
      valueType: "text",
      defaultValue: "",
    },

    // ── Body & Weight ─────────────────────────────────────────
    {
      id: "body",
      name: "Body Shell",
      category: "Body & Weight",
      valueType: "text",
      defaultValue: "",
    },
    {
      id: "body-weight",
      name: "Body Weight",
      category: "Body & Weight",
      valueType: "numeric",
      min: 0,
      max: 30,
      step: 0.1,
      unit: "g",
      defaultValue: 0,
    },
    {
      id: "ballast-total",
      name: "Ballast Total",
      category: "Body & Weight",
      valueType: "numeric",
      min: 0,
      max: 50,
      step: 0.5,
      unit: "g",
      defaultValue: 0,
    },
    {
      id: "ballast-position",
      name: "Ballast Position",
      category: "Body & Weight",
      valueType: "text",
      defaultValue: "",
    },
    {
      id: "total-weight",
      name: "Total Weight",
      category: "Body & Weight",
      valueType: "numeric",
      min: 100,
      max: 300,
      step: 0.5,
      unit: "g",
      defaultValue: 170,
    },
  ],

  compatibilityRules: [],

  defaultSetup: {
    "chassis-plate": "carbon",
    "motor-pod": "standard",
    "front-spring": "medium",
    "front-ride-height": 2.5,
    "front-camber": -1,
    "front-toe": 1,
    "front-caster": "4",
    "front-kingpin-angle": "6",
    "t-plate": "medium",
    "front-knuckle": "stock",
    "front-damper": "friction",
    "rear-spring": "medium",
    "rear-ride-height": 2.5,
    "rear-camber": -1.5,
    "rear-damper": "friction",
    "pinion-gear": 11,
    "spur-gear": 48,
    "diff-type": "ball",
    "diff-tension": "medium",
    "front-tire": "marka-v1-25",
    "rear-tire": "marka-v1-25",
    "front-wheel": "offset-0",
    "rear-wheel": "offset-0",
    "motor": "5600kv Brushless",
    "esc": "",
    "servo": "",
    "battery": "",
    "radio": "",
    "receiver": "",
    "transponder": "",
    "body": "",
    "body-weight": 0,
    "ballast-total": 0,
    "ballast-position": "",
    "total-weight": 170,
  },
};
