import type { CarDefinition } from "../models.js";

/**
 * Kyosho Mini-Z MR-03 RWD — full capability-driven car definition.
 *
 * References:
 *  - Kyosho MR-03 setup sheet (MR-03_setupSheet_blank-en.pdf)
 *  - docs/kyosho-mr03rwd.md
 *  - docs/tires.md (tire / wheel inventory)
 */
export const mr03Rwd: CarDefinition = {
  id: "car-mr03-rwd",
  slug: "kyosho-mr03-rwd",
  name: "MR-03 RWD",
  manufacturer: "Kyosho",
  scale: "1:28",
  driveType: "RWD",

  capabilities: [
    // ── Front Suspension ──────────────────────────────────────
    {
      id: "front-spring",
      name: "Front Spring",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "Soft (Gold)", value: "soft-gold", color: "#d4a017" },
        { label: "Medium (Blue)", value: "medium-blue", color: "#3b82f6" },
        { label: "Hard (Red)", value: "hard-red", color: "#ef4444" },
        { label: "Extra Hard (Green)", value: "x-hard-green", color: "#22c55e" },
      ],
    },
    {
      id: "front-ride-height",
      name: "Front Ride Height",
      category: "Front Suspension",
      valueType: "numeric",
      min: 0,
      max: 5,
      step: 0.1,
      unit: "mm",
      defaultValue: 2.0,
    },
    {
      id: "front-camber",
      name: "Front Camber",
      category: "Front Suspension",
      valueType: "numeric",
      min: -3,
      max: 0,
      step: 0.5,
      unit: "°",
      defaultValue: -1,
      description: "Negative = top of tire leaning in",
    },
    {
      id: "front-toe",
      name: "Front Toe",
      category: "Front Suspension",
      valueType: "numeric",
      min: -2,
      max: 4,
      step: 0.5,
      unit: "°",
      defaultValue: 1,
      description: "Positive = toe-out",
    },
    {
      id: "front-caster",
      name: "Front Caster",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "0°", value: "0" },
        { label: "1°", value: "1" },
        { label: "2°", value: "2" },
        { label: "3°", value: "3" },
        { label: "4°", value: "4" },
        { label: "5°", value: "5" },
      ],
      defaultValue: "2",
    },
    {
      id: "front-kingpin-angle",
      name: "Kingpin Angle",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "0°", value: "0" },
        { label: "3°", value: "3" },
        { label: "6°", value: "6" },
        { label: "8°", value: "8" },
      ],
      defaultValue: "6",
    },
    {
      id: "front-t-plate",
      name: "T-Plate",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "Standard (Stock)", value: "standard" },
        { label: "Carbon #2 (Soft)", value: "carbon-2-soft" },
        { label: "Carbon #3 (Soft/Medium)", value: "carbon-3-soft-medium" },
        { label: "Carbon #4 (Medium/Hard)", value: "carbon-4-medium-hard" },
        { label: "Carbon #5 (Hard)", value: "carbon-5-hard" },
        { label: "FRP #6S (Soft)", value: "frp-6s" },
        { label: "FRP #6M (Medium)", value: "frp-6m" },
        { label: "FRP #6H (Hard)", value: "frp-6h" },
        { label: "Carbon Soft", value: "carbon-soft" },
        { label: "Carbon Medium", value: "carbon-medium" },
        { label: "Carbon Hard", value: "carbon-hard" },
      ],
      defaultValue: "standard",
      description: "T-plate stiffness controls rear roll and side-bite. Carbon is stiffer than FRP at same rating.",
    },
    {
      id: "front-knuckle",
      name: "Front Knuckle",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "Stock", value: "stock" },
        { label: "Aluminum", value: "aluminum" },
        { label: "Carbon", value: "carbon" },
      ],
      defaultValue: "stock",
    },

    // ── Rear Suspension ───────────────────────────────────────
    {
      id: "rear-spring",
      name: "Rear Spring",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "Soft (Gold)", value: "soft-gold", color: "#d4a017" },
        { label: "Medium (Blue)", value: "medium-blue", color: "#3b82f6" },
        { label: "Hard (Red)", value: "hard-red", color: "#ef4444" },
        { label: "Extra Hard (Green)", value: "x-hard-green", color: "#22c55e" },
      ],
    },
    {
      id: "rear-ride-height",
      name: "Rear Ride Height",
      category: "Rear Suspension",
      valueType: "numeric",
      min: 0,
      max: 5,
      step: 0.1,
      unit: "mm",
      defaultValue: 2.5,
    },
    {
      id: "rear-camber",
      name: "Rear Camber",
      category: "Rear Suspension",
      valueType: "numeric",
      min: -3,
      max: 0,
      step: 0.5,
      unit: "°",
      defaultValue: -1,
      description: "Negative = top of tire leaning in",
    },

    // ── Dampers ───────────────────────────────────────────────
    {
      id: "front-damper",
      name: "Front Oil Damper",
      category: "Dampers",
      valueType: "pick",
      options: [
        { label: "None / Friction", value: "friction" },
        { label: "Oil Damper", value: "oil" },
      ],
      defaultValue: "friction",
    },
    {
      id: "front-damper-oil",
      name: "Front Damper Oil Weight",
      category: "Dampers",
      valueType: "pick",
      options: [
        { label: "#200", value: "200" },
        { label: "#300", value: "300" },
        { label: "#400", value: "400" },
        { label: "#500", value: "500" },
        { label: "#600", value: "600" },
        { label: "#700", value: "700" },
        { label: "#800", value: "800" },
      ],
      description: "Only applicable when oil damper is installed",
    },
    {
      id: "rear-damper",
      name: "Rear Friction Plate",
      category: "Dampers",
      valueType: "pick",
      options: [
        { label: "Standard", value: "standard" },
        { label: "Heavy", value: "heavy" },
      ],
      defaultValue: "standard",
    },
    {
      id: "rear-damper-grease",
      name: "Rear Damper Grease",
      category: "Dampers",
      valueType: "pick",
      options: [
        { label: "None", value: "none" },
        { label: "Kyosho #1000", value: "k-1000" },
        { label: "Kyosho #3000", value: "k-3000" },
        { label: "Kyosho #5000", value: "k-5000" },
        { label: "Kyosho #15000", value: "k-15000" },
        { label: "Kyosho #30000", value: "k-30000" },
      ],
    },

    // ── Motor Mount & Drivetrain ───────────────────────────────
    {
      id: "motor-mount",
      name: "Motor Mount Position",
      category: "Drivetrain",
      valueType: "pick",
      options: [
        { label: "MM (98 mm)", value: "mm-98" },
        { label: "LM (102 mm)", value: "lm-102" },
      ],
      defaultValue: "mm-98",
    },
    {
      id: "pinion-gear",
      name: "Pinion Gear",
      category: "Drivetrain",
      valueType: "pick",
      options: [
        { label: "6T", value: "6" },
        { label: "7T", value: "7" },
        { label: "8T", value: "8" },
        { label: "9T", value: "9" },
        { label: "10T", value: "10" },
        { label: "11T", value: "11" },
        { label: "12T", value: "12" },
        { label: "13T", value: "13" },
        { label: "14T", value: "14" },
      ],
      defaultValue: "8",
    },
    {
      id: "spur-gear",
      name: "Spur Gear",
      category: "Drivetrain",
      valueType: "pick",
      options: [
        { label: "38T", value: "38" },
        { label: "39T", value: "39" },
        { label: "40T", value: "40" },
        { label: "41T", value: "41" },
        { label: "42T", value: "42" },
        { label: "43T", value: "43" },
        { label: "44T", value: "44" },
        { label: "46T", value: "46" },
        { label: "48T", value: "48" },
        { label: "50T", value: "50" },
        { label: "53T", value: "53" },
      ],
      defaultValue: "42",
    },
    {
      id: "diff-type",
      name: "Differential",
      category: "Drivetrain",
      valueType: "pick",
      options: [
        { label: "Spool (locked)", value: "spool" },
        { label: "Ball Diff", value: "ball-diff" },
        { label: "Gear Diff", value: "gear-diff" },
      ],
      defaultValue: "ball-diff",
    },

    // ── Electronics ────────────────────────────────────────────
    {
      id: "motor",
      name: "Motor",
      category: "Electronics",
      valueType: "text",
      defaultValue: "Stock",
    },
    {
      id: "esc",
      name: "ESC",
      category: "Electronics",
      valueType: "text",
      defaultValue: "Stock",
    },
    {
      id: "servo",
      name: "Servo",
      category: "Electronics",
      valueType: "text",
    },
    {
      id: "battery",
      name: "Battery",
      category: "Electronics",
      valueType: "text",
      defaultValue: "AAA NiMH",
    },

    // ── Body ──────────────────────────────────────────────────
    {
      id: "body",
      name: "Body Shell",
      category: "Body",
      valueType: "text",
    },
    {
      id: "body-weight",
      name: "Body Weight",
      category: "Body",
      valueType: "numeric",
      min: 0,
      max: 80,
      step: 0.1,
      unit: "g",
    },

    // ── Ballast ────────────────────────────────────────────────
    {
      id: "ballast-total",
      name: "Total Ballast",
      category: "Weight",
      valueType: "numeric",
      min: 0,
      max: 50,
      step: 0.5,
      unit: "g",
      defaultValue: 0,
    },
    {
      id: "ballast-position",
      name: "Ballast Position",
      category: "Weight",
      valueType: "text",
      description: "Where ballast is placed (e.g. 'under servo', 'front bumper')",
    },
  ],

  compatibilityRules: [
    {
      id: "mr03-front-damper-oil",
      description: "Front damper oil weight only available when oil damper is installed",
      when: { capabilityId: "front-damper", value: "friction" },
      then: { deny: { capabilityId: "front-damper-oil", values: ["200", "300", "400", "500", "600", "700", "800"] } },
    },
    {
      id: "mr03-mm-pinion-max",
      description: "MM motor mount limited to max 11T pinion",
      when: { capabilityId: "motor-mount", value: "mm-98" },
      then: { deny: { capabilityId: "pinion-gear", values: ["12", "13", "14"] } },
    },
  ],

  defaultSetup: {
    "front-spring": "medium-blue",
    "front-ride-height": 2.0,
    "front-camber": -1,
    "front-toe": 1,
    "front-caster": "2",
    "front-kingpin-angle": "6",
    "front-t-plate": "standard",
    "front-knuckle": "stock",
    "rear-spring": "medium-blue",
    "rear-ride-height": 2.5,
    "rear-camber": -1,
    "front-damper": "friction",
    "rear-damper": "standard",
    "motor-mount": "mm-98",
    "pinion-gear": "8",
    "spur-gear": "42",
    "diff-type": "ball-diff",
    "battery": "AAA NiMH",
    "ballast-total": 0,
  },
};
