import type { CarDefinition } from "../models.js";

/**
 * Atomic RC MRX Master Edition — full capability-driven car definition.
 *
 * References:
 *  - docs/AtomicMRXME.md
 *  - Atomic RC MRX Master Edition manual
 */
export const mrxMasterEdition: CarDefinition = {
  id: "car-mrx-me",
  slug: "atomic-mrx-me",
  name: "MRX Master Edition",
  manufacturer: "Atomic RC",
  scale: "1:28",
  driveType: "RWD",

  capabilities: [
    // ── Chassis ───────────────────────────────────────────────
    {
      id: "chassis",
      name: "Chassis",
      category: "Chassis",
      valueType: "pick",
      options: [
        { label: "Stock Plastic", value: "plastic" },
        { label: "Aluminum (MRXME UP10, 12g)", value: "aluminum", sku: "MRXME UP10" },
        { label: "Brass (MRXME 04)", value: "brass", sku: "MRXME 04" },
      ],
      defaultValue: "plastic",
    },
    {
      id: "side-wing",
      name: "Side Wing",
      category: "Chassis",
      valueType: "pick",
      options: [
        { label: "None", value: "none" },
        { label: "Small (58 mm)", value: "small-58mm" },
      ],
      defaultValue: "none",
    },

    // ── Front Suspension ──────────────────────────────────────
    {
      id: "front-ride-height",
      name: "Front Ride Height",
      category: "Front Suspension",
      valueType: "numeric",
      min: 0,
      max: 5,
      step: 0.1,
      unit: "mm",
      defaultValue: 2.1,
    },
    {
      id: "front-daa-spring",
      name: "Front DAA Spring",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "Super Soft (Red)", value: "super-soft-red", color: "#ef4444", sku: "MRXME UP02SS" },
        { label: "Soft (White)", value: "soft-white", color: "#f5f5f5", sku: "MRXME UP02S" },
        { label: "Medium (Yellow)", value: "medium-yellow", color: "#eab308", sku: "MRXME UP02M" },
        { label: "Hard (Purple)", value: "hard-purple", color: "#a855f7", sku: "MRXME UP02H" },
      ],
      defaultValue: "super-soft-red",
    },
    {
      id: "front-damper-grease",
      name: "Front Damper Grease",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "None", value: "none" },
        { label: "Atomic 15000", value: "atomic-15000" },
        { label: "Atomic 25000", value: "atomic-25000" },
        { label: "Atomic 35000", value: "atomic-35000" },
        { label: "Atomic 45000", value: "atomic-45000" },
        { label: "Reflex 250000", value: "reflex-250000" },
        { label: "Kyosho 1000", value: "kyosho-1000" },
        { label: "Kyosho 3000", value: "kyosho-3000" },
        { label: "Kyosho 5000", value: "kyosho-5000" },
        { label: "Kyosho 15000", value: "kyosho-15000" },
        { label: "Kyosho 30000", value: "kyosho-30000" },
      ],
      defaultValue: "atomic-25000",
    },
    {
      id: "front-toe",
      name: "Front Toe",
      category: "Front Suspension",
      valueType: "numeric",
      min: -2,
      max: 6,
      step: 0.5,
      unit: "° out",
      defaultValue: 4,
      description: "Positive = toe-out",
    },
    {
      id: "front-caster",
      name: "Caster",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "0°", value: "0" },
        { label: "1°", value: "1" },
        { label: "2°", value: "2" },
        { label: "3°", value: "3" },
        { label: "4°", value: "4" },
        { label: "5°", value: "5" },
      ],
      defaultValue: "2",
    },
    {
      id: "top-kingpin-shim",
      name: "Top Kingpin Shim",
      category: "Front Suspension",
      valueType: "numeric",
      min: 0,
      max: 5,
      step: 1,
      unit: "shims",
      defaultValue: 0,
    },
    {
      id: "bottom-kingpin-shim",
      name: "Bottom Kingpin Shim",
      category: "Front Suspension",
      valueType: "numeric",
      min: 0,
      max: 5,
      step: 1,
      unit: "shims",
      defaultValue: 2,
    },
    {
      id: "front-damper-shim",
      name: "Front Damper Shim",
      category: "Front Suspension",
      valueType: "numeric",
      min: 0,
      max: 5,
      step: 1,
      unit: "shims",
      defaultValue: 1,
    },
    {
      id: "front-knuckle",
      name: "Front Knuckle / Axles",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "Stock Axles", value: "stock" },
        { label: "Aluminum Knuckles V2", value: "aluminum-v2" },
      ],
      defaultValue: "aluminum-v2",
    },

    // ── Rear Suspension ───────────────────────────────────────
    {
      id: "rear-ride-height",
      name: "Rear Ride Height",
      category: "Rear Suspension",
      valueType: "numeric",
      min: 0,
      max: 5,
      step: 0.1,
      unit: "mm",
      defaultValue: 3.2,
    },
    {
      id: "rear-spring-style",
      name: "Rear Spring Style",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "Horizontal", value: "horizontal" },
        { label: "Vertical Side Springs", value: "vertical" },
      ],
      defaultValue: "horizontal",
    },
    {
      id: "vertical-side-spring",
      name: "Vertical Side Spring",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "N/A", value: "na" },
        { label: "Soft (Green)", value: "soft-green", color: "#22c55e", sku: "MRXME UP01S" },
        { label: "Medium (Red)", value: "medium-red", color: "#ef4444", sku: "MRXME UP01M" },
        { label: "Hard (Yellow)", value: "hard-yellow", color: "#eab308", sku: "MRXME UP01H" },
      ],
      defaultValue: "na",
      description: "Only applicable when vertical side spring style is selected",
    },
    {
      id: "rear-top-spring",
      name: "Rear Top Spring",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "None", value: "none" },
        { label: "Soft (White)", value: "soft-white", color: "#f5f5f5", sku: "MRXME UP05S" },
        { label: "Medium (Yellow)", value: "medium-yellow", color: "#eab308", sku: "MRXME UP05M" },
        { label: "Hard (Purple)", value: "hard-purple", color: "#a855f7", sku: "MRXME UP05H" },
      ],
      defaultValue: "medium-yellow",
    },
    {
      id: "center-damper-grease",
      name: "Center Damper Grease",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "None", value: "none" },
        { label: "Atomic 15000", value: "atomic-15000" },
        { label: "Atomic 25000", value: "atomic-25000" },
        { label: "Atomic 35000", value: "atomic-35000" },
        { label: "Atomic 45000", value: "atomic-45000" },
        { label: "Reflex 250000", value: "reflex-250000" },
        { label: "Kyosho 1000", value: "kyosho-1000" },
        { label: "Kyosho 3000", value: "kyosho-3000" },
        { label: "Kyosho 5000", value: "kyosho-5000" },
        { label: "Kyosho 15000", value: "kyosho-15000" },
        { label: "Kyosho 30000", value: "kyosho-30000" },
      ],
      defaultValue: "atomic-25000",
    },
    {
      id: "side-spring-damper-grease",
      name: "Side Spring Damper Grease",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "None", value: "none" },
        { label: "Atomic 15000", value: "atomic-15000" },
        { label: "Atomic 25000", value: "atomic-25000" },
        { label: "Atomic 35000", value: "atomic-35000" },
        { label: "Atomic 45000", value: "atomic-45000" },
        { label: "Reflex 250000", value: "reflex-250000" },
      ],
      defaultValue: "atomic-25000",
    },
    {
      id: "center-damper",
      name: "Center Damper",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "Standard", value: "standard" },
        { label: "With Droop Adjustment (MRXME UP08)", value: "droop-adj", sku: "MRXME UP08" },
      ],
      defaultValue: "standard",
    },
    {
      id: "center-damper-mount",
      name: "Center Damper Mount",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "Standard", value: "standard" },
        { label: "24 mm Battery Mount (MRXME UP09)", value: "24mm-battery", sku: "MRXME UP09" },
      ],
      defaultValue: "standard",
    },

    // ── Drivetrain ────────────────────────────────────────────
    {
      id: "pinion-gear",
      name: "Pinion Gear",
      category: "Drivetrain",
      valueType: "pick",
      options: [
        { label: "8T", value: "8" },
        { label: "9T", value: "9" },
        { label: "10T", value: "10" },
        { label: "11T", value: "11" },
        { label: "12T", value: "12" },
        { label: "13T", value: "13" },
        { label: "14T", value: "14" },
      ],
      defaultValue: "12",
    },
    {
      id: "spur-gear",
      name: "Spur Gear",
      category: "Drivetrain",
      valueType: "pick",
      options: [
        { label: "48T", value: "48" },
        { label: "50T", value: "50" },
        { label: "53T (Atomic Stock)", value: "53" },
        { label: "55T", value: "55" },
      ],
      defaultValue: "53",
    },
    {
      id: "diff-type",
      name: "Differential",
      category: "Drivetrain",
      valueType: "pick",
      options: [
        { label: "Spool (locked)", value: "spool" },
        { label: "Ball Diff", value: "ball-diff" },
        { label: "Gear Diff (Atomic Stock)", value: "gear-diff" },
      ],
      defaultValue: "gear-diff",
    },
    {
      id: "diff-tension",
      name: "Diff Tension",
      category: "Drivetrain",
      valueType: "pick",
      options: [
        { label: "N/A (spool)", value: "na" },
        { label: "Tight (fully tightened, back off 1/8 turn)", value: "tight" },
        { label: "Medium (back off 1/4 turn)", value: "medium" },
        { label: "Loose (back off 1/2 turn)", value: "loose" },
      ],
      defaultValue: "tight",
      description: "Tighten fully, then back off. Barking = too loose. Binding = too tight.",
    },

    // ── Tires ──────────────────────────────────────────────────
    {
      id: "front-tire",
      name: "Front Tire",
      category: "Tires & Wheels",
      valueType: "pick",
      options: [
        { label: "Marka V5 Front 25° / 11 mm", value: "marka-v5-front-25-11" },
        { label: "Kyosho 30 Front 8.5 mm", value: "kyosho-30-front-85" },
        { label: "Gekko FM-GK-002 8.5 mm", value: "gekko-fm-gk002" },
        { label: "Gekko FS-GK-001 8.5 mm", value: "gekko-fs-gk001" },
      ],
      defaultValue: "marka-v5-front-25-11",
    },
    {
      id: "rear-tire",
      name: "Rear Tire",
      category: "Tires & Wheels",
      valueType: "pick",
      options: [
        { label: "Marka MZR V1RR15 14 mm", value: "marka-mzr-v1rr15-14" },
        { label: "Kyosho 30 Rear 11 mm", value: "kyosho-30-rear-11" },
        { label: "Kyosho 20 Rear 11 mm", value: "kyosho-20-rear-11" },
        { label: "Gekko RM1-GK-004 11 mm", value: "gekko-rm1-gk004" },
        { label: "Gekko RS1-GK-003 11 mm", value: "gekko-rs1-gk003" },
      ],
      defaultValue: "marka-mzr-v1rr15-14",
    },
    {
      id: "front-wheel",
      name: "Front Wheel",
      category: "Tires & Wheels",
      valueType: "pick",
      options: [
        { label: "Silver Horse EVO \"JUD\" 8.5 mm +1", value: "sh-jud-85-p1" },
        { label: "Silver Horse EVO \"JUD\" 8.5 mm +0", value: "sh-jud-85-p0" },
        { label: "Silver Horse EVO \"JUD\" 8.5 mm -1", value: "sh-jud-85-n1" },
        { label: "PN MR2088 Delrin (PNWC)", value: "pn-mr2088-delrin" },
      ],
      defaultValue: "sh-jud-85-p1",
    },
    {
      id: "rear-wheel",
      name: "Rear Wheel",
      category: "Tires & Wheels",
      valueType: "pick",
      options: [
        { label: "Silver Horse EVO \"JUD\" 11 mm +3", value: "sh-jud-11-p3" },
        { label: "Silver Horse EVO \"JUD\" 11 mm +2", value: "sh-jud-11-p2" },
        { label: "Silver Horse EVO \"JUD\" 11 mm +1", value: "sh-jud-11-p1" },
        { label: "Silver Horse EVO \"JUD\" 11 mm +0", value: "sh-jud-11-p0" },
        { label: "PN MR2089 Delrin (PNWC)", value: "pn-mr2089-delrin" },
      ],
      defaultValue: "sh-jud-11-p3",
    },
    {
      id: "tire-glue",
      name: "Tire Glue / Mount",
      category: "Tires & Wheels",
      valueType: "pick",
      options: [
        { label: "None (friction fit)", value: "none" },
        { label: "Double-sided tape", value: "tape" },
        { label: "CA glue (full)", value: "ca-full" },
        { label: "CA glue (edge only)", value: "ca-edge" },
      ],
      defaultValue: "none",
    },

    // ── Electronics ────────────────────────────────────────────
    {
      id: "motor",
      name: "Motor",
      category: "Electronics",
      valueType: "text",
      defaultValue: "PN Anima V4 2500kv",
    },
    {
      id: "esc",
      name: "ESC",
      category: "Electronics",
      valueType: "text",
      defaultValue: "Hobbywing EZRun Mini28",
    },
    {
      id: "servo",
      name: "Servo",
      category: "Electronics",
      valueType: "text",
      defaultValue: "AGFRC A06CLS v2",
    },
    {
      id: "battery",
      name: "Battery",
      category: "Electronics",
      valueType: "text",
      defaultValue: "Silver Horse RC 450mAh 2S 7.4V 60C",
    },
    {
      id: "radio",
      name: "Radio",
      category: "Electronics",
      valueType: "text",
      defaultValue: "Flysky Noble 4 Plus",
    },
    {
      id: "receiver",
      name: "Receiver",
      category: "Electronics",
      valueType: "text",
      defaultValue: "Micro 4-channel",
    },
    {
      id: "transponder",
      name: "Lap Timing",
      category: "Electronics",
      valueType: "text",
      defaultValue: "EasyLap Transponder",
    },

    // ── Body ──────────────────────────────────────────────────
    {
      id: "body",
      name: "Body Shell",
      category: "Body",
      valueType: "text",
    },
    {
      id: "body-weight",
      name: "Body Weight",
      category: "Body",
      valueType: "numeric",
      min: 0,
      max: 80,
      step: 0.1,
      unit: "g",
    },

    // ── Ballast ────────────────────────────────────────────────
    {
      id: "ballast-total",
      name: "Total Ballast",
      category: "Weight",
      valueType: "numeric",
      min: 0,
      max: 50,
      step: 0.5,
      unit: "g",
      defaultValue: 0,
    },
    {
      id: "ballast-position",
      name: "Ballast Position",
      category: "Weight",
      valueType: "text",
      description: "Where ballast is placed",
    },
    {
      id: "total-weight",
      name: "Total Car Weight",
      category: "Weight",
      valueType: "numeric",
      min: 0,
      max: 300,
      step: 0.1,
      unit: "g",
      description: "PNWC minimum: 140 g",
    },
  ],

  compatibilityRules: [
    {
      id: "mrx-vertical-spring-na",
      description: "Vertical side springs only applicable when rear style is vertical",
      when: { capabilityId: "rear-spring-style", value: "horizontal" },
      then: { deny: { capabilityId: "vertical-side-spring", values: ["soft-green", "medium-red", "hard-yellow"] } },
    },
    {
      id: "mrx-pnwc-gearing",
      description: "PNWC requires 12/53 gearing (64 pitch)",
      when: { capabilityId: "pinion-gear", value: "12" },
      then: { allow: { capabilityId: "spur-gear", values: ["53"] } },
    },
  ],

  defaultSetup: {
    "chassis": "plastic",
    "side-wing": "none",
    "front-ride-height": 2.1,
    "front-daa-spring": "super-soft-red",
    "front-damper-grease": "atomic-25000",
    "front-toe": 4,
    "front-caster": "2",
    "top-kingpin-shim": 0,
    "bottom-kingpin-shim": 2,
    "front-damper-shim": 1,
    "front-knuckle": "aluminum-v2",
    "rear-ride-height": 3.2,
    "rear-spring-style": "horizontal",
    "vertical-side-spring": "na",
    "rear-top-spring": "medium-yellow",
    "center-damper-grease": "atomic-25000",
    "side-spring-damper-grease": "atomic-25000",
    "center-damper": "standard",
    "center-damper-mount": "standard",
    "pinion-gear": "12",
    "spur-gear": "53",
    "diff-type": "gear-diff",
    "diff-tension": "tight",
    "front-tire": "marka-v5-front-25-11",
    "rear-tire": "marka-mzr-v1rr15-14",
    "front-wheel": "sh-jud-85-p1",
    "rear-wheel": "sh-jud-11-p3",
    "tire-glue": "none",
    "motor": "PN Anima V4 2500kv",
    "esc": "Hobbywing EZRun Mini28",
    "servo": "AGFRC A06CLS v2",
    "battery": "Silver Horse RC 450mAh 2S 7.4V 60C",
    "radio": "Flysky Noble 4 Plus",
    "receiver": "Micro 4-channel",
    "transponder": "EasyLap Transponder",
    "ballast-total": 0,
  },
};
