import type { CarDefinition } from "../models.js";

/**
 * Reflex Racing RX28 — full capability-driven car definition.
 *
 * The RX28 is a damper/spring-focused 1:28 RWD chassis featuring true coilover
 * dampers (front and rear), adjustable ride height via threaded shock bodies,
 * and a low CG design optimised for high-grip carpet/RCP tracks.
 */
export const reflexRx28: CarDefinition = {
  id: "car-rx28",
  slug: "reflex-rx28",
  name: "RX28",
  manufacturer: "Reflex Racing",
  scale: "1:28",
  driveType: "RWD",

  capabilities: [
    // ── Chassis ───────────────────────────────────────────────
    {
      id: "chassis-plate",
      name: "Chassis Plate",
      category: "Chassis",
      valueType: "pick",
      options: [
        { label: "Standard FRP", value: "frp" },
        { label: "Carbon Fiber", value: "carbon" },
        { label: "Aluminum", value: "aluminum" },
      ],
      defaultValue: "frp",
    },
    {
      id: "motor-pod",
      name: "Motor Pod",
      category: "Chassis",
      valueType: "pick",
      options: [
        { label: "Standard", value: "standard" },
        { label: "Lightweight", value: "lightweight" },
      ],
      defaultValue: "standard",
    },

    // ── Front Suspension ──────────────────────────────────────
    {
      id: "front-spring",
      name: "Front Spring",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "Super Soft (Gold)", value: "super-soft-gold", color: "#d4a017" },
        { label: "Soft (Silver)", value: "soft-silver", color: "#c0c0c0" },
        { label: "Medium (Blue)", value: "medium-blue", color: "#3b82f6" },
        { label: "Hard (Red)", value: "hard-red", color: "#ef4444" },
        { label: "Extra Hard (Black)", value: "x-hard-black", color: "#333333" },
      ],
      defaultValue: "medium-blue",
    },
    {
      id: "front-damper-oil",
      name: "Front Damper Oil",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "#200", value: "200" },
        { label: "#300", value: "300" },
        { label: "#400", value: "400" },
        { label: "#500", value: "500" },
        { label: "#600", value: "600" },
        { label: "#700", value: "700" },
        { label: "#800", value: "800" },
      ],
      defaultValue: "400",
      description: "Coilover damper oil weight (cst)",
    },
    {
      id: "front-ride-height",
      name: "Front Ride Height",
      category: "Front Suspension",
      valueType: "numeric",
      min: 0,
      max: 6,
      step: 0.1,
      unit: "mm",
      defaultValue: 2.0,
      description: "Adjusted via threaded shock body preload",
    },
    {
      id: "front-droop",
      name: "Front Droop",
      category: "Front Suspension",
      valueType: "numeric",
      min: 0,
      max: 4,
      step: 0.5,
      unit: "mm",
      defaultValue: 1.5,
      description: "Maximum downward suspension travel",
    },
    {
      id: "front-camber",
      name: "Front Camber",
      category: "Front Suspension",
      valueType: "numeric",
      min: -3,
      max: 0,
      step: 0.5,
      unit: "°",
      defaultValue: -1,
      description: "Negative = top of tire leaning in",
    },
    {
      id: "front-toe",
      name: "Front Toe",
      category: "Front Suspension",
      valueType: "numeric",
      min: -2,
      max: 4,
      step: 0.5,
      unit: "°",
      defaultValue: 1,
      description: "Positive = toe-out",
    },
    {
      id: "front-caster",
      name: "Front Caster",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "0°", value: "0" },
        { label: "2°", value: "2" },
        { label: "4°", value: "4" },
        { label: "6°", value: "6" },
        { label: "8°", value: "8" },
      ],
      defaultValue: "4",
    },
    {
      id: "front-kingpin-angle",
      name: "Kingpin Angle",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "0°", value: "0" },
        { label: "3°", value: "3" },
        { label: "6°", value: "6" },
        { label: "8°", value: "8" },
      ],
      defaultValue: "6",
    },
    {
      id: "front-knuckle",
      name: "Front Knuckle",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "Stock Plastic", value: "stock" },
        { label: "Aluminum", value: "aluminum" },
      ],
      defaultValue: "stock",
    },
    {
      id: "front-rebound",
      name: "Front Rebound",
      category: "Front Suspension",
      valueType: "pick",
      options: [
        { label: "Free", value: "free" },
        { label: "1 O-ring", value: "1-oring" },
        { label: "2 O-rings", value: "2-oring" },
      ],
      defaultValue: "free",
      description: "Rebound clips / O-rings on the damper shaft",
    },

    // ── Rear Suspension ───────────────────────────────────────
    {
      id: "rear-spring",
      name: "Rear Spring",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "Super Soft (Gold)", value: "super-soft-gold", color: "#d4a017" },
        { label: "Soft (Silver)", value: "soft-silver", color: "#c0c0c0" },
        { label: "Medium (Blue)", value: "medium-blue", color: "#3b82f6" },
        { label: "Hard (Red)", value: "hard-red", color: "#ef4444" },
        { label: "Extra Hard (Black)", value: "x-hard-black", color: "#333333" },
      ],
      defaultValue: "medium-blue",
    },
    {
      id: "rear-damper-oil",
      name: "Rear Damper Oil",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "#200", value: "200" },
        { label: "#300", value: "300" },
        { label: "#400", value: "400" },
        { label: "#500", value: "500" },
        { label: "#600", value: "600" },
        { label: "#700", value: "700" },
        { label: "#800", value: "800" },
      ],
      defaultValue: "500",
      description: "Coilover damper oil weight (cst)",
    },
    {
      id: "rear-ride-height",
      name: "Rear Ride Height",
      category: "Rear Suspension",
      valueType: "numeric",
      min: 0,
      max: 6,
      step: 0.1,
      unit: "mm",
      defaultValue: 2.5,
      description: "Adjusted via threaded shock body preload",
    },
    {
      id: "rear-droop",
      name: "Rear Droop",
      category: "Rear Suspension",
      valueType: "numeric",
      min: 0,
      max: 4,
      step: 0.5,
      unit: "mm",
      defaultValue: 1.5,
      description: "Maximum downward suspension travel",
    },
    {
      id: "rear-camber",
      name: "Rear Camber",
      category: "Rear Suspension",
      valueType: "numeric",
      min: -3,
      max: 0,
      step: 0.5,
      unit: "°",
      defaultValue: -1,
      description: "Negative = top of tire leaning in",
    },
    {
      id: "rear-toe",
      name: "Rear Toe",
      category: "Rear Suspension",
      valueType: "numeric",
      min: -1,
      max: 3,
      step: 0.5,
      unit: "°",
      defaultValue: 1,
      description: "Positive = toe-in (typical for rear stability)",
    },
    {
      id: "rear-rebound",
      name: "Rear Rebound",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "Free", value: "free" },
        { label: "1 O-ring", value: "1-oring" },
        { label: "2 O-rings", value: "2-oring" },
      ],
      defaultValue: "free",
      description: "Rebound clips / O-rings on the damper shaft",
    },
    {
      id: "rear-pod-pivot",
      name: "Rear Pod Pivot",
      category: "Rear Suspension",
      valueType: "pick",
      options: [
        { label: "Loose", value: "loose" },
        { label: "Standard", value: "standard" },
        { label: "Tight", value: "tight" },
      ],
      defaultValue: "standard",
      description: "Pod pivot point friction / preload",
    },

    // ── Drivetrain ────────────────────────────────────────────
    {
      id: "pinion-gear",
      name: "Pinion Gear",
      category: "Drivetrain",
      valueType: "pick",
      options: [
        { label: "6T", value: "6" },
        { label: "7T", value: "7" },
        { label: "8T", value: "8" },
        { label: "9T", value: "9" },
        { label: "10T", value: "10" },
        { label: "11T", value: "11" },
        { label: "12T", value: "12" },
        { label: "13T", value: "13" },
        { label: "14T", value: "14" },
      ],
      defaultValue: "9",
    },
    {
      id: "spur-gear",
      name: "Spur Gear",
      category: "Drivetrain",
      valueType: "pick",
      options: [
        { label: "38T", value: "38" },
        { label: "39T", value: "39" },
        { label: "40T", value: "40" },
        { label: "41T", value: "41" },
        { label: "42T", value: "42" },
        { label: "43T", value: "43" },
        { label: "44T", value: "44" },
        { label: "46T", value: "46" },
        { label: "48T", value: "48" },
      ],
      defaultValue: "42",
    },
    {
      id: "diff-type",
      name: "Differential",
      category: "Drivetrain",
      valueType: "pick",
      options: [
        { label: "Spool (locked)", value: "spool" },
        { label: "Ball Diff", value: "ball-diff" },
      ],
      defaultValue: "ball-diff",
    },
    {
      id: "diff-tension",
      name: "Ball Diff Tension",
      category: "Drivetrain",
      valueType: "pick",
      options: [
        { label: "N/A (spool)", value: "na" },
        { label: "Loose", value: "loose" },
        { label: "Medium", value: "medium" },
        { label: "Tight", value: "tight" },
      ],
      defaultValue: "medium",
      description: "Only applicable with ball diff",
    },

    // ── Electronics ────────────────────────────────────────────
    {
      id: "motor",
      name: "Motor",
      category: "Electronics",
      valueType: "text",
      defaultValue: "Stock",
    },
    {
      id: "esc",
      name: "ESC",
      category: "Electronics",
      valueType: "text",
      defaultValue: "Stock",
    },
    {
      id: "servo",
      name: "Servo",
      category: "Electronics",
      valueType: "text",
    },
    {
      id: "battery",
      name: "Battery",
      category: "Electronics",
      valueType: "text",
      defaultValue: "AAA NiMH",
    },
    {
      id: "radio",
      name: "Radio",
      category: "Electronics",
      valueType: "text",
    },

    // ── Body ──────────────────────────────────────────────────
    {
      id: "body",
      name: "Body Shell",
      category: "Body",
      valueType: "text",
    },
    {
      id: "body-weight",
      name: "Body Weight",
      category: "Body",
      valueType: "numeric",
      min: 0,
      max: 80,
      step: 0.1,
      unit: "g",
    },

    // ── Ballast ────────────────────────────────────────────────
    {
      id: "ballast-total",
      name: "Total Ballast",
      category: "Weight",
      valueType: "numeric",
      min: 0,
      max: 50,
      step: 0.5,
      unit: "g",
      defaultValue: 0,
    },
    {
      id: "ballast-position",
      name: "Ballast Position",
      category: "Weight",
      valueType: "text",
      description: "Where ballast is placed (e.g. 'under servo', 'front bumper')",
    },
    {
      id: "total-weight",
      name: "Total Car Weight",
      category: "Weight",
      valueType: "numeric",
      min: 0,
      max: 300,
      step: 0.1,
      unit: "g",
    },
  ],

  compatibilityRules: [
    {
      id: "rx28-diff-tension-spool",
      description: "Ball diff tension only applicable when ball diff is installed",
      when: { capabilityId: "diff-type", value: "spool" },
      then: { deny: { capabilityId: "diff-tension", values: ["loose", "medium", "tight"] } },
    },
  ],

  defaultSetup: {
    "chassis-plate": "frp",
    "motor-pod": "standard",
    "front-spring": "medium-blue",
    "front-damper-oil": "400",
    "front-ride-height": 2.0,
    "front-droop": 1.5,
    "front-camber": -1,
    "front-toe": 1,
    "front-caster": "4",
    "front-kingpin-angle": "6",
    "front-knuckle": "stock",
    "front-rebound": "free",
    "rear-spring": "medium-blue",
    "rear-damper-oil": "500",
    "rear-ride-height": 2.5,
    "rear-droop": 1.5,
    "rear-camber": -1,
    "rear-toe": 1,
    "rear-rebound": "free",
    "rear-pod-pivot": "standard",
    "pinion-gear": "9",
    "spur-gear": "42",
    "diff-type": "ball-diff",
    "diff-tension": "medium",
    "battery": "AAA NiMH",
    "ballast-total": 0,
  },
};
